### ISSUE TITLE
homepage.html

### ISSUE THREAD

**Issue by crisanlucid** [YiwenLiCatherine/gallery-web#2]
```css
<style>
* {
  box-sizing: border-box;
}

body {
  font-family: Arial, Helvetica, sans-serif;
}

/* Style the header */
header {
  background-color: #009;
  padding: 30px;
  text-align: center;
  font-size: 35px;
  color: white;
}

/* Create two columns/boxes that floats next to each other */
nav {
  float: left;
  width: 30%;
  height: 300px; /* only for demonstration, should be removed */
  background: #ccc;
  padding: 20px;
}

/* Style the list inside the menu */
nav ul {
  list-style-type: none;
  padding: 0;
}

article {
  float: left;
  padding: 20px;
  width: 70%;
  background-color: #f1f1f1;
  height: 300px; /* only for demonstration, should be removed */
}

/* Clear floats after the columns */
section:after {
  content: "";
  display: table;
  clear: both;
}

/* Style the footer */
footer {
  background-color: #777;
  padding: 10px;
  text-align: center;
  color: white;
}

/* Responsive layout - makes the two columns/boxes stack on top of each other instead of next to each other, on small screens */
@media (max-width: 600px) {
  nav, article {
    width: 100%;
    height: auto;
  }
}</style>
```

@YiwenLiCatherine please have a look: 

1) the style should be in separate file CSS.  it great to have clean code :   a) styling into css files; b) HTML tags in HTML file c) animation in Javascript files

```html
<section>
  <nav>
    <ul>
      <li><a href="#">Cat</a></li>
      <li><a href="#">Dog</a></li>
      <li><a href="#">Fox</a></li>
    </ul>
  </nav>
  
  <article>
    <h1>Cat</h1>
    <p>The cat (Felis catus) is a domestic species of small carnivorous mammal. It is the only domesticated species in the family Felidae and is often referred to as the domestic cat to distinguish it from the wild members of the family. A cat can either be a house cat, a farm cat or a feral cat; the latter ranges freely and avoids human contact.Domestic cats are valued by humans for companionship and their ability to hunt rodents. About 60 cat breeds are recognized by various cat registries.
    </p>
    <p>Here you can see more....</p>
  </article>
</section>
```
2) ```Replace <section> tag with <main>  https://developer.mozilla.org/en-US/docs/Web/HTML/Element/main ```

3) should be an order in heading H1, H2 , H3    not:   h2, h1, h2
